#Put your address in here... so you don't have to check it in
#This is not my real address.  Drop me a message on github if you need
#my contact info
address: "1060 W Addison \#1\\\Chicago, IL 60613\\\(312) 222-9595\\\myemailaddress@wowzers.org"
